version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    version_requirement_updates: "increase_versions"
    default_labels:
      - "dependabot"
    allowed_updates:
      - match:
          update_type: "all"

  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    version_requirement_updates: "increase_versions"
    default_labels:
      - "dependabot"
    allowed_updates:
      - match:
          update_type: "all"
